// Generated by ts-to-zod
import { z } from "zod";
import { type Json } from "./../../database.types.clean";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() => z.union([z.string(), z.number(), z.boolean(), z.record(z.string(), z.union([jsonSchema, z.undefined()])), z.array(jsonSchema)]).nullable());

export const databaseSchema = z.object({
    public: z.object({
        Tables: z.object({
            admin_users: z.object({
                Row: z.object({
                    id: z.string(),
                    email: z.string(),
                    role: z.union([z.literal("super_admin"), z.literal("admin"), z.literal("receptionist")]),
                    display_name: z.string().nullable(),
                    created_at: z.string()
                }),
                Insert: z.object({
                    id: z.string().optional(),
                    email: z.string(),
                    role: z.union([z.literal("super_admin"), z.literal("admin"), z.literal("receptionist")]).optional(),
                    display_name: z.string().optional().nullable(),
                    created_at: z.string().optional()
                }),
                Update: z.object({
                    id: z.string().optional(),
                    email: z.string().optional(),
                    role: z.union([z.literal("super_admin"), z.literal("admin"), z.literal("receptionist")]).optional(),
                    display_name: z.string().optional().nullable(),
                    created_at: z.string().optional()
                }),
                Relationships: z.tuple([])
            }),
            appointments: z.object({
                Row: z.object({
                    id: z.string(),
                    patient_id: z.string(),
                    patient_name: z.string().nullable(),
                    patient_phone: z.string().nullable(),
                    appointment_date: z.string(),
                    appointment_time: z.string().nullable(),
                    type: z.string().nullable(),
                    status: z.string().nullable(),
                    notes: z.string().nullable(),
                    booked_by: z.string().nullable(),
                    daily_number: z.number().nullable(),
                    duration: z.number().nullable(),
                    created_at: z.string(),
                    updated_at: z.string()
                }),
                Insert: z.object({
                    id: z.string().optional(),
                    patient_id: z.string(),
                    patient_name: z.string().optional().nullable(),
                    patient_phone: z.string().optional().nullable(),
                    appointment_date: z.string(),
                    appointment_time: z.string().optional().nullable(),
                    type: z.string().optional().nullable(),
                    status: z.string().optional().nullable(),
                    notes: z.string().optional().nullable(),
                    booked_by: z.string().optional().nullable(),
                    daily_number: z.number().optional().nullable(),
                    duration: z.number().optional().nullable(),
                    created_at: z.string().optional(),
                    updated_at: z.string().optional()
                }),
                Update: z.object({
                    id: z.string().optional(),
                    patient_id: z.string().optional(),
                    patient_name: z.string().optional().nullable(),
                    patient_phone: z.string().optional().nullable(),
                    appointment_date: z.string().optional(),
                    appointment_time: z.string().optional().nullable(),
                    type: z.string().optional().nullable(),
                    status: z.string().optional().nullable(),
                    notes: z.string().optional().nullable(),
                    booked_by: z.string().optional().nullable(),
                    daily_number: z.number().optional().nullable(),
                    duration: z.number().optional().nullable(),
                    created_at: z.string().optional(),
                    updated_at: z.string().optional()
                }),
                Relationships: z.tuple([])
            }),
            audit_logs: z.object({
                Row: z.object({
                    id: z.string(),
                    user_id: z.string().nullable(),
                    user_email: z.string().nullable(),
                    user_role: z.string().nullable(),
                    action: z.string(),
                    entity_type: z.string(),
                    entity_id: z.string().nullable(),
                    old_values: jsonSchema.nullable(),
                    new_values: jsonSchema.nullable(),
                    reason: z.string().nullable(),
                    created_at: z.string()
                }),
                Insert: z.object({
                    id: z.string().optional(),
                    user_id: z.string().optional().nullable(),
                    user_email: z.string().optional().nullable(),
                    user_role: z.string().optional().nullable(),
                    action: z.string(),
                    entity_type: z.string(),
                    entity_id: z.string().optional().nullable(),
                    old_values: jsonSchema.optional().nullable(),
                    new_values: jsonSchema.optional().nullable(),
                    reason: z.string().optional().nullable(),
                    created_at: z.string().optional()
                }),
                Update: z.object({
                    id: z.string().optional(),
                    user_id: z.string().optional().nullable(),
                    user_email: z.string().optional().nullable(),
                    user_role: z.string().optional().nullable(),
                    action: z.string().optional(),
                    entity_type: z.string().optional(),
                    entity_id: z.string().optional().nullable(),
                    old_values: jsonSchema.optional().nullable(),
                    new_values: jsonSchema.optional().nullable(),
                    reason: z.string().optional().nullable(),
                    created_at: z.string().optional()
                }),
                Relationships: z.tuple([])
            }),
            closures: z.object({
                Row: z.object({
                    id: z.string(),
                    start_date: z.string(),
                    end_date: z.string(),
                    reason: z.string().nullable(),
                    created_at: z.string()
                }),
                Insert: z.object({
                    id: z.string().optional(),
                    start_date: z.string(),
                    end_date: z.string(),
                    reason: z.string().optional().nullable(),
                    created_at: z.string().optional()
                }),
                Update: z.object({
                    id: z.string().optional(),
                    start_date: z.string().optional(),
                    end_date: z.string().optional(),
                    reason: z.string().optional().nullable(),
                    created_at: z.string().optional()
                }),
                Relationships: z.tuple([])
            }),
            daily_counters: z.object({
                Row: z.object({
                    date: z.string(),
                    count: z.number()
                }),
                Insert: z.object({
                    date: z.string(),
                    count: z.number().optional()
                }),
                Update: z.object({
                    date: z.string().optional(),
                    count: z.number().optional()
                }),
                Relationships: z.tuple([])
            }),
            installments: z.object({
                Row: z.object({
                    id: z.string(),
                    invoice_id: z.string(),
                    patient_id: z.string(),
                    amount: z.number(),
                    due_date: z.string(),
                    paid_date: z.string().nullable(),
                    paid: z.boolean(),
                    notes: z.string().nullable(),
                    created_at: z.string(),
                    updated_at: z.string()
                }),
                Insert: z.object({
                    id: z.string().optional(),
                    invoice_id: z.string(),
                    patient_id: z.string(),
                    amount: z.number(),
                    due_date: z.string(),
                    paid_date: z.string().optional().nullable(),
                    paid: z.boolean().optional(),
                    notes: z.string().optional().nullable(),
                    created_at: z.string().optional(),
                    updated_at: z.string().optional()
                }),
                Update: z.object({
                    id: z.string().optional(),
                    invoice_id: z.string().optional(),
                    patient_id: z.string().optional(),
                    amount: z.number().optional(),
                    due_date: z.string().optional(),
                    paid_date: z.string().optional().nullable(),
                    paid: z.boolean().optional(),
                    notes: z.string().optional().nullable(),
                    created_at: z.string().optional(),
                    updated_at: z.string().optional()
                }),
                Relationships: z.tuple([])
            }),
            invoices: z.object({
                Row: z.object({
                    id: z.string(),
                    patient_id: z.string(),
                    patient_name: z.string().nullable(),
                    appointment_id: z.string().nullable(),
                    invoice_number: z.string().nullable(),
                    subtotal: z.number(),
                    discount: z.number(),
                    discount_reason: z.string().nullable(),
                    total_amount: z.number(),
                    total_paid: z.number(),
                    balance: z.number(),
                    status: z.string().nullable(),
                    items: jsonSchema.nullable(),
                    payments: jsonSchema.nullable(),
                    notes: z.string().nullable(),
                    invoice_date: z.string(),
                    created_at: z.string(),
                    updated_at: z.string()
                }),
                Insert: z.object({
                    id: z.string().optional(),
                    patient_id: z.string(),
                    patient_name: z.string().optional().nullable(),
                    appointment_id: z.string().optional().nullable(),
                    invoice_number: z.string().optional().nullable(),
                    subtotal: z.number().optional(),
                    discount: z.number().optional(),
                    discount_reason: z.string().optional().nullable(),
                    total_amount: z.number().optional(),
                    total_paid: z.number().optional(),
                    balance: z.number().optional(),
                    status: z.string().optional().nullable(),
                    items: jsonSchema.optional().nullable(),
                    payments: jsonSchema.optional().nullable(),
                    notes: z.string().optional().nullable(),
                    invoice_date: z.string().optional(),
                    created_at: z.string().optional(),
                    updated_at: z.string().optional()
                }),
                Update: z.object({
                    id: z.string().optional(),
                    patient_id: z.string().optional(),
                    patient_name: z.string().optional().nullable(),
                    appointment_id: z.string().optional().nullable(),
                    invoice_number: z.string().optional().nullable(),
                    subtotal: z.number().optional(),
                    discount: z.number().optional(),
                    discount_reason: z.string().optional().nullable(),
                    total_amount: z.number().optional(),
                    total_paid: z.number().optional(),
                    balance: z.number().optional(),
                    status: z.string().optional().nullable(),
                    items: jsonSchema.optional().nullable(),
                    payments: jsonSchema.optional().nullable(),
                    notes: z.string().optional().nullable(),
                    invoice_date: z.string().optional(),
                    created_at: z.string().optional(),
                    updated_at: z.string().optional()
                }),
                Relationships: z.tuple([])
            }),
            landing_content: z.object({
                Row: z.object({
                    id: z.string(),
                    section: z.string(),
                    key: z.string(),
                    content: z.string().nullable(),
                    type: z.string().nullable(),
                    updated_at: z.string()
                }),
                Insert: z.object({
                    id: z.string(),
                    section: z.string(),
                    key: z.string(),
                    content: z.string().optional().nullable(),
                    type: z.string().optional().nullable(),
                    updated_at: z.string().optional()
                }),
                Update: z.object({
                    id: z.string().optional(),
                    section: z.string().optional(),
                    key: z.string().optional(),
                    content: z.string().optional().nullable(),
                    type: z.string().optional().nullable(),
                    updated_at: z.string().optional()
                }),
                Relationships: z.tuple([])
            }),
            medical_records: z.object({
                Row: z.object({
                    id: z.string(),
                    patient_id: z.string(),
                    appointment_id: z.string().nullable(),
                    visit_date: z.string().nullable(),
                    chief_complaint: z.string().nullable(),
                    diagnosis: z.string().nullable(),
                    treatment_done: z.string().nullable(),
                    treatment_plan: z.string().nullable(),
                    teeth_chart: jsonSchema.nullable(),
                    prescription: z.string().nullable(),
                    xray_report: z.string().nullable(),
                    lab_report: z.string().nullable(),
                    doctor_notes: z.string().nullable(),
                    follow_up_date: z.string().nullable(),
                    attachments: jsonSchema.nullable(),
                    created_at: z.string(),
                    updated_at: z.string()
                }),
                Insert: z.object({
                    id: z.string().optional(),
                    patient_id: z.string(),
                    appointment_id: z.string().optional().nullable(),
                    visit_date: z.string().optional().nullable(),
                    chief_complaint: z.string().optional().nullable(),
                    diagnosis: z.string().optional().nullable(),
                    treatment_done: z.string().optional().nullable(),
                    treatment_plan: z.string().optional().nullable(),
                    teeth_chart: jsonSchema.optional().nullable(),
                    prescription: z.string().optional().nullable(),
                    xray_report: z.string().optional().nullable(),
                    lab_report: z.string().optional().nullable(),
                    doctor_notes: z.string().optional().nullable(),
                    follow_up_date: z.string().optional().nullable(),
                    attachments: jsonSchema.optional().nullable(),
                    created_at: z.string().optional(),
                    updated_at: z.string().optional()
                }),
                Update: z.object({
                    id: z.string().optional(),
                    patient_id: z.string().optional(),
                    appointment_id: z.string().optional().nullable(),
                    visit_date: z.string().optional().nullable(),
                    chief_complaint: z.string().optional().nullable(),
                    diagnosis: z.string().optional().nullable(),
                    treatment_done: z.string().optional().nullable(),
                    treatment_plan: z.string().optional().nullable(),
                    teeth_chart: jsonSchema.optional().nullable(),
                    prescription: z.string().optional().nullable(),
                    xray_report: z.string().optional().nullable(),
                    lab_report: z.string().optional().nullable(),
                    doctor_notes: z.string().optional().nullable(),
                    follow_up_date: z.string().optional().nullable(),
                    attachments: jsonSchema.optional().nullable(),
                    created_at: z.string().optional(),
                    updated_at: z.string().optional()
                }),
                Relationships: z.tuple([])
            }),
            patients: z.object({
                Row: z.object({
                    id: z.string(),
                    name: z.string(),
                    phone: z.string().nullable(),
                    email: z.string().nullable(),
                    date_of_birth: z.string().nullable(),
                    gender: z.string().nullable(),
                    address: z.string().nullable(),
                    medical_history: jsonSchema.nullable(),
                    is_active: z.boolean(),
                    created_at: z.string(),
                    updated_at: z.string()
                }),
                Insert: z.object({
                    id: z.string().optional(),
                    name: z.string(),
                    phone: z.string().optional().nullable(),
                    email: z.string().optional().nullable(),
                    date_of_birth: z.string().optional().nullable(),
                    gender: z.string().optional().nullable(),
                    address: z.string().optional().nullable(),
                    medical_history: jsonSchema.optional().nullable(),
                    is_active: z.boolean().optional(),
                    created_at: z.string().optional(),
                    updated_at: z.string().optional()
                }),
                Update: z.object({
                    id: z.string().optional(),
                    name: z.string().optional(),
                    phone: z.string().optional().nullable(),
                    email: z.string().optional().nullable(),
                    date_of_birth: z.string().optional().nullable(),
                    gender: z.string().optional().nullable(),
                    address: z.string().optional().nullable(),
                    medical_history: jsonSchema.optional().nullable(),
                    is_active: z.boolean().optional(),
                    created_at: z.string().optional(),
                    updated_at: z.string().optional()
                }),
                Relationships: z.tuple([])
            }),
            settings: z.object({
                Row: z.object({
                    id: z.number(),
                    clinic_name: z.string().nullable(),
                    doctor_name: z.string().nullable(),
                    phone: z.string().nullable(),
                    whatsapp: z.string().nullable(),
                    address: z.string().nullable(),
                    working_days: z.array(z.number()).nullable(),
                    shifts: jsonSchema.nullable(),
                    slot_duration: z.number().nullable(),
                    max_daily_appointments: z.number().nullable(),
                    is_booking_enabled: z.boolean().nullable(),
                    booking_advance_days: z.number().nullable(),
                    created_at: z.string(),
                    updated_at: z.string()
                }),
                Insert: z.object({
                    id: z.number().optional(),
                    clinic_name: z.string().optional().nullable(),
                    doctor_name: z.string().optional().nullable(),
                    phone: z.string().optional().nullable(),
                    whatsapp: z.string().optional().nullable(),
                    address: z.string().optional().nullable(),
                    working_days: z.array(z.number()).optional().nullable(),
                    shifts: jsonSchema.optional().nullable(),
                    slot_duration: z.number().optional().nullable(),
                    max_daily_appointments: z.number().optional().nullable(),
                    is_booking_enabled: z.boolean().optional().nullable(),
                    booking_advance_days: z.number().optional().nullable(),
                    created_at: z.string().optional(),
                    updated_at: z.string().optional()
                }),
                Update: z.object({
                    id: z.number().optional(),
                    clinic_name: z.string().optional().nullable(),
                    doctor_name: z.string().optional().nullable(),
                    phone: z.string().optional().nullable(),
                    whatsapp: z.string().optional().nullable(),
                    address: z.string().optional().nullable(),
                    working_days: z.array(z.number()).optional().nullable(),
                    shifts: jsonSchema.optional().nullable(),
                    slot_duration: z.number().optional().nullable(),
                    max_daily_appointments: z.number().optional().nullable(),
                    is_booking_enabled: z.boolean().optional().nullable(),
                    booking_advance_days: z.number().optional().nullable(),
                    created_at: z.string().optional(),
                    updated_at: z.string().optional()
                }),
                Relationships: z.tuple([])
            }),
            slot_locks: z.object({
                Row: z.object({
                    id: z.string(),
                    lock_key: z.string(),
                    session_id: z.string(),
                    expires_at: z.string(),
                    created_at: z.string()
                }),
                Insert: z.object({
                    id: z.string().optional(),
                    lock_key: z.string(),
                    session_id: z.string(),
                    expires_at: z.string(),
                    created_at: z.string().optional()
                }),
                Update: z.object({
                    id: z.string().optional(),
                    lock_key: z.string().optional(),
                    session_id: z.string().optional(),
                    expires_at: z.string().optional(),
                    created_at: z.string().optional()
                }),
                Relationships: z.tuple([])
            })
        }),
        Views: z.any(),
        Functions: z.object({
            book_appointment_safe: z.object({
                Args: z.object({
                    p_patient_id: z.string(),
                    p_date: z.string(),
                    p_time: z.string(),
                    p_type: z.string(),
                    p_notes: z.string(),
                    p_session_id: z.string(),
                    p_lock_id: z.string(),
                    p_max_daily: z.number()
                }),
                Returns: jsonSchema
            }),
            log_audit_trail: z.object({
                Args: z.object({
                    p_user_id: z.string(),
                    p_user_email: z.string(),
                    p_user_role: z.string(),
                    p_action: z.string(),
                    p_entity_type: z.string(),
                    p_entity_id: z.string(),
                    p_old_values: jsonSchema.optional(),
                    p_new_values: jsonSchema.optional(),
                    p_reason: z.string().optional()
                }),
                Returns: z.undefined()
            })
        }),
        Enums: z.any(),
        CompositeTypes: z.any()
    })
});
